name: E_GlassOldConstWideHybrid3
resultsDir: '../../../results/E_Glass/hybrid/'
virtualExperiment: False
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: True
outputParams:
  saveAllSamples: False
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 25
  file: '../../../data/E_Glass/E_GlassOldConstNominal_0_cone_Mass.csv'
  time: 0
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 8
optimizeParams:
  opP: 12
  opS: 24
  opQ: 6
  opAlpha: 3
  opBeta: 3
  minP: 2
  minIter: 5
  maxIter: 1000
  absErr: 1e-7
  relErr: 1e-12
  absRelErr: 5e-7
  relIter: 15
  maxTime: 60000
  elimThresh: 1e-2
phaseParams:
  phases: ['virgin', 'char']
  C0:   [[1,      0,      1], [0,  1189,   1189]      ]
  ka:   [[0.3,     0.27,   0.33], [0.2,  0.18,  0.22]   ]
  kb:   [[0.0,      0.0,    0.0], [0.0,  0.0,   0.0]     ]
  kc:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  kd:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  rho:  [[1683,  1189,   1189], [1235,  1189,   1189]   ]
  Cpa:  [[1500,     1350,   1650], [1100,  990,   1210]   ]
  Cpb:  [[0.0,      0.0,    0.0], [0.0,  1189,   1189]    ]
  Cpc:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  Cpd:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  eps:  [[None,     0.235,   1.0], [None,  0.235,   1.0]    ]
  K:    [[10000,    2500,    40000], [1e8,  1189,   1189]   ]
  nO2:  [[0,        0,      1], [0,  1189,   1189]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[None,2.106e12,2.574e12]]
  E:   [[None,1.629e5,1.991e5]]
  n:   [[None,0.9,1.1]]
  Hp:  [[None,9e04,1.1e5]]
  nO2: [[0,0,1]]
  Xi:  [[None,0,1]]
  typeState: [3]
  reacState: [0]
  prodState: [1]
