name: multiReacCharLinearWide100KW
resultsDir: '../../../results/multiReactionCharring/validation/'
virtualExperiment: True
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: False
keepTemporaryFiles: True
outputParams:
  saveAllSamples: True
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 100
  file: '../../../data/multiReactionCharring/multiReacCharLinearNominal100KW_0_cone_Mass.csv'
  time: 0
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 8
phaseParams:
  phases: ['virgin', 'char']
  C0:   [[1,      0,      1], [0,  1189,   1189]      ]
  ka:   [[0.31267,     0.10,   0.30], [0.21,  1189,   1189]   ]
  kb:   [[2.4217e-5,      0.0,    0.0], [1.0e-4,  0.0,   0.0]     ]
  kc:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  kd:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  rho:  [[1683,  1189,   1189], [1235,  1189,   1189]   ]
  Cpa:  [[1068.97,     1000,   2800], [295.72,  1189,   1189]   ]
  Cpb:  [[1.13e-2,      0.0,    0.0], [1.034,  1189,   1189]    ]
  Cpc:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  Cpd:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  eps:  [[0.9384,     0.75,   1.0], [0.94,  1189,   1189]    ]
  K:    [[3713,     500,    3000], [1e8,  1189,   1189]   ]
  nO2:  [[0,        0,      1], [0,  1189,   1189]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[7.13e12,1e6,1e14], [2.95e14,1e6,1e14]]
  E:   [[1.81e5,1.2e4,2.0e5], [7.43e5,1.2e4,2.0e5]]
  n:   [[1.2237,5e-1,4e0], [0.3797,5e-1,4e0]]
  Hp:  [[168625,1e5,1e7], [206799,1e5,1e7]]
  nO2: [[0,0,1], [0,0,1]]
  Xi:  [[0.75,0,1], [0.5,0,1]]
  typeState: [3,3]
  reacState: [0,0]
  prodState: [1,1]
