name: charLinear2Reac2Mass10kW
resultsDir: '../../../../results/multiReactionCharring/2Reactions/validation/'
virtualExperiment: True
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: False
keepTemporaryFiles: True
outputParams:
  saveAllSamples: True
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 10
  file: '../../../../data/multiReactionCharring/multiReactionCharringFake1.csv'
  time: 0
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 8
phaseParams:
  phases: ['virgin', 'char']
  C0:   [[1,      0,      1], [0,  1189,   1189]      ]
  ka:   [[0.2877,     0.10,   0.30], [0.0994,  1189,   1189]   ]
  kb:   [[7.134e-5,      0.0,    0.0], [2.02e-4,  0.0,   0.0]     ]
  kc:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  kd:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  rho:  [[1683,  1189,   1189], [1235,  1189,   1189]   ]
  Cpa:  [[1099.38,     1000,   2800], [262.27,  1189,   1189]   ]
  Cpb:  [[0.1035,      0.0,    0.0], [0.07086,  1189,   1189]    ]
  Cpc:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  Cpd:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  eps:  [[0.8614,     0.75,   1.0], [0.94,  1189,   1189]    ]
  K:    [[28167.5,     500,    3000], [1e8,  1189,   1189]   ]
  nO2:  [[0,        0,      1], [0,  1189,   1189]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[4.05e12,1e6,1e14], [4.02e13,1e6,1e14]]
  E:   [[1.70e5,1.2e4,2.0e5], [3.5e5,1.2e4,2.0e5]]
  n:   [[2.288,5e-1,4e0], [4.105,5e-1,4e0]]
  Hp:  [[167766,1e5,1e7], [389743,1e5,1e7]]
  nO2: [[0,0,1], [0,0,1]]
  Xi:  [[0.5789,0,1], [0.5689,0,1]]
  typeState: [3,3]
  reacState: [0,0]
  prodState: [1,1]
