name: charLinear2ReacBT100kW
resultsDir: '../../../../results/multiReactionCharring/2Reactions/validation/'
virtualExperiment: True
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: False
keepTemporaryFiles: True
outputParams:
  saveAllSamples: True
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 100
  file: '../../../../data/multiReactionCharring/multiReactionCharringFake.csv'
  time: 0
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 8
phaseParams:
  phases: ['virgin', 'char']
  C0:   [[1,      0,      1], [0,  1189,   1189]      ]
  ka:   [[0.3094,     0.10,   0.30], [0.1399,  1189,   1189]   ]
  kb:   [[7.62e-5,      0.0,    0.0], [2.044e-4,  0.0,   0.0]     ]
  kc:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  kd:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  rho:  [[1683,  1189,   1189], [1235,  1189,   1189]   ]
  Cpa:  [[1081.5,     1000,   2800], [730.6,  1189,   1189]   ]
  Cpb:  [[0.1146,      0.0,    0.0], [0.665,  1189,   1189]    ]
  Cpc:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  Cpd:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  eps:  [[0.9616,     0.75,   1.0], [0.94,  1189,   1189]    ]
  K:    [[39998.8,     500,    3000], [1e8,  1189,   1189]   ]
  nO2:  [[0,        0,      1], [0,  1189,   1189]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[5.21e12,1e6,1e14], [1.88e13,1e6,1e14]]
  E:   [[1.78e5,1.2e4,2.0e5], [2.24e5,1.2e4,2.0e5]]
  n:   [[1.236,5e-1,4e0], [2.205,5e-1,4e0]]
  Hp:  [[166029,1e5,1e7], [397450,1e5,1e7]]
  nO2: [[0,0,1], [0,0,1]]
  Xi:  [[0.582,0,1], [0.641,0,1]]
  typeState: [3,3]
  reacState: [0,0]
  prodState: [1,1]
