cone1:
  Tinit: 25
  activePhaseVars:
  - C0
  - rho
  - ka
  - kb
  - kc
  - kd
  - ke
  - Cpa
  - Cpb
  - Cpc
  - Cpd
  - Cpe
  - eps
  - K
  activeReactionVars:
  - A
  - E
  - n
  - Hp
  - nO2
  - Xi
  backBoundaryConditions:
    Tamb: 25
    htc: Auto
    type: INSULATED
  columns:
  - 1
  depths:
  - 0
  file: C:/Users/fcyan/workspace/JH/optimizationPaper/data/multiReactionCharring/multiReactionCharringFake.csv
  frontBoundaryConditions:
    Tamb: 25
    heatFlux: 60.0
    htc: 15
  initialThickness: 0.008
  names:
  - Mass
  time: 0
  types:
  - 1
  weight: 1.0
  weights:
  - 1
  width1: 0.1016
  width2: 0.1016
dataSources:
  names:
  - cone1
  types:
  - cone
fdsPath: C:\Program Files\FDS\FDS6\bin
keepTemporaryFiles: true
name: charLinear3Reac1Mass60kW
outputParams:
  saveAllSamples: true
phaseParams:
  C0:
  - - 1
    - 0
    - 1
  - - 0
    - 1189
    - 1189
  Cpa:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - &id001 !!python/object/apply:numpy.dtype
        args:
        - f8
        - 0
        - 1
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        x+4saRWYokA=
    - 1000
    - 2800
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        V+n5r0CxqUA=
    - 1189
    - 1189
  Cpb:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        LQoWTqPJuj8=
    - 0.0
    - 0.0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        FOq+YjBO3j8=
    - 1189
    - 1189
  Cpc:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  Cpd:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  K:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        J2JIndhw0kA=
    - 500
    - 3000
  - - 1e8
    - 1189
    - 1189
  eps:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        0qzgxewb6T8=
    - 0.75
    - 1.0
  - - 0.94
    - 1189
    - 1189
  ka:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        oATJ8bQE4z8=
    - 0.1
    - 0.3
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        +FVjEaUSuz8=
    - 1189
    - 1189
  kb:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        xvvtD9H0Cj8=
    - 0.0
    - 0.0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        Ngs2BZ1oLz8=
    - 0.0
    - 0.0
  kc:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  kd:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  nO2:
  - - 0
    - 0
    - 1
  - - 0
    - 1189
    - 1189
  phases:
  - virgin
  - char
  rho:
  - - 1683
    - 1189
    - 1189
  - - 1235
    - 1189
    - 1189
processParams:
  maxProcesses: 8
  multiprocess: true
reactionParams:
  A:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AABAisPBiUI=
    - 1e6
    - 1e14
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AABMO3GwwEI=
    - 1e6
    - 1e14
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AACYJZjTskI=
    - 1e6
    - 1e14
  E:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAEC5AEE=
    - 1.2e4
    - 2.0e5
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAMD3AEE=
    - 1.2e4
    - 2.0e5
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAIBVAUE=
    - 1.2e4
    - 2.0e5
  Hp:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        ZZb6HqssBkE=
    - 1e5
    - 1e7
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        OS6PlFtgGkE=
    - 1e5
    - 1e7
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        eR6xi2VUKEE=
    - 1e5
    - 1e7
  Xi:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        et77PgrG3T8=
    - 0
    - 1
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        CaMnfQrd2z8=
    - 0
    - 1
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        DZfIbeaX2T8=
    - 0
    - 1
  n:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        3BGMRjgFAkA=
    - 5e-1
    - 4e0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        ie2nR1DD+D8=
    - 5e-1
    - 4e0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        qXBvzv9VGEA=
    - 5e-1
    - 4e0
  nO2:
  - - 0
    - 0
    - 1
  - - 0
    - 0
    - 1
  - - 0
    - 0
    - 1
  prodState:
  - 1
  - 1
  - 1
  reacState:
  - 0
  - 0
  - 0
  typeState:
  - 3
  - 3
  - 3
reinitializeComplex: false
resultsDir: ../../../../results/multiReactionCharring/3Reactions/validation/
virtualExperiment: true
