cone1:
  Tinit: 25
  activePhaseVars:
  - C0
  - rho
  - ka
  - kb
  - kc
  - kd
  - ke
  - Cpa
  - Cpb
  - Cpc
  - Cpd
  - Cpe
  - eps
  - K
  activeReactionVars:
  - A
  - E
  - n
  - Hp
  - nO2
  - Xi
  backBoundaryConditions:
    Tamb: 25
    htc: Auto
    type: INSULATED
  columns:
  - 1
  depths:
  - 0
  file: C:/Users/Fyang/Workspace/optimization/optimizationPaper/data/multiReactionCharring/multiReactionCharringFake1.csv
  frontBoundaryConditions:
    Tamb: 25
    heatFlux: 10.0
    htc: 15
  initialThickness: 0.008
  names:
  - Mass
  time: 0
  types:
  - 1
  weight: 1.0
  weights:
  - 1
  width1: 0.1016
  width2: 0.1016
dataSources:
  names:
  - cone1
  types:
  - cone
fdsPath: C:\Program Files\FDS\FDS6\bin
keepTemporaryFiles: true
name: charLinear3ReacTGA10kW
outputParams:
  saveAllSamples: true
phaseParams:
  C0:
  - - 1
    - 0
    - 1
  - - 0
    - 1189
    - 1189
  Cpa:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - &id001 !!python/object/apply:numpy.dtype
        args:
        - f8
        - 0
        - 1
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        1hnaa5Kmj0A=
    - 1000
    - 2800
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        6CyBRPsIiUA=
    - 1189
    - 1189
  Cpb:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        xMlbeU+Lvz8=
    - 0.0
    - 0.0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        tMTrcvMB0z8=
    - 1189
    - 1189
  Cpc:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  Cpd:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  K:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        KLeEXeHi00A=
    - 500
    - 3000
  - - 1e8
    - 1189
    - 1189
  eps:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AYfq3dtH7T8=
    - 0.75
    - 1.0
  - - 0.94
    - 1189
    - 1189
  ka:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        gs20xS720j8=
    - 0.1
    - 0.3
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        qVu5ZVIGtz8=
    - 1189
    - 1189
  kb:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        UiHgsFB5DD8=
    - 0.0
    - 0.0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        TALDQ5dJND8=
    - 0.0
    - 0.0
  kc:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  kd:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  nO2:
  - - 0
    - 0
    - 1
  - - 0
    - 1189
    - 1189
  phases:
  - virgin
  - char
  rho:
  - - 1683
    - 1189
    - 1189
  - - 1235
    - 1189
    - 1189
processParams:
  maxProcesses: 8
  multiprocess: true
reactionParams:
  A:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AACAsdcrgUI=
    - 1e6
    - 1e14
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AACQZKbq0EI=
    - 1e6
    - 1e14
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AACYQYx/oEI=
    - 1e6
    - 1e14
  E:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAMBWBkE=
    - 1.2e4
    - 2.0e5
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAEASB0E=
    - 1.2e4
    - 2.0e5
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAB8BUE=
    - 1.2e4
    - 2.0e5
  Hp:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        SIDsoW+HDEE=
    - 1e5
    - 1e7
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        /3Wv0Q9DDkE=
    - 1e5
    - 1e7
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        Nv3cTgmBF0E=
    - 1e5
    - 1e7
  Xi:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        EF1SMOpn6D8=
    - 0
    - 1
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        bQt/f6BF3z8=
    - 0
    - 1
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        dL7H8AEB0z8=
    - 0
    - 1
  n:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        LdAelvkw8D8=
    - 5e-1
    - 4e0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        eT4JYpT99z8=
    - 5e-1
    - 4e0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        MS3TAymWB0A=
    - 5e-1
    - 4e0
  nO2:
  - - 0
    - 0
    - 1
  - - 0
    - 0
    - 1
  - - 0
    - 0
    - 1
  prodState:
  - 1
  - 1
  - 1
  reacState:
  - 0
  - 0
  - 0
  typeState:
  - 3
  - 3
  - 3
reinitializeComplex: false
resultsDir: ../../../../results/multiReactionCharring/3Reactions/validation/
virtualExperiment: true
