name: charLinear3Reac2Mass10kW
resultsDir: '../../../../results/multiReactionCharring/3Reactions/validation/'
virtualExperiment: True
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: False
keepTemporaryFiles: True
outputParams:
  saveAllSamples: True
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 10
  file: '../../../../data/multiReactionCharring/multiReactionCharringFake1.csv'
  time: 0
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 8
phaseParams:
  phases: ['virgin', 'char']
  C0:   [[1,      0,      1], [0,  1189,   1189]      ]
  ka:   [[0.406,     0.10,   0.30], [0.167,  1189,   1189]   ]
  kb:   [[7.13e-5,      0.0,    0.0], [4.78e-4,  0.0,   0.0]     ]
  kc:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  kd:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  rho:  [[1683,  1189,   1189], [1235,  1189,   1189]   ]
  Cpa:  [[1506.78,     1000,   2800], [2638.3,  1189,   1189]   ]
  Cpb:  [[9.294e-2,      0.0,    0.0], [5.437e-1,  1189,   1189]    ]
  Cpc:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  Cpd:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  eps:  [[0.705,     0.75,   1.0], [0.94,  1189,   1189]    ]
  K:    [[19298.6,     500,    3000], [1e8,  1189,   1189]   ]
  nO2:  [[0,        0,      1], [0,  1189,   1189]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[3.88e12,1e6,1e14], [9.95e13,1e6,1e14], [1.32e13,1e6,1e14]]
  E:   [[1.56e5,1.2e4,2.0e5], [1.49e5,1.2e4,2.0e5], [2.85e5,1.2e4,2.0e5]]
  n:   [[2.02,5e-1,4e0], [2.7,5e-1,4e0], [7.29,5e-1,4e0]]
  Hp:  [[272682.04,1e5,1e7], [473951.8,1e5,1e7], [831263.9,1e5,1e7]]
  nO2: [[0,0,1], [0,0,1], [0,0,1]]
  Xi:  [[0.498,0,1], [0.437,0,1], [0.489,0,1]]
  typeState: [3,3,3]
  reacState: [0,0,0]
  prodState: [1,1,1]
