cone1:
  Tinit: 25
  activePhaseVars:
  - C0
  - rho
  - ka
  - kb
  - kc
  - kd
  - ke
  - Cpa
  - Cpb
  - Cpc
  - Cpd
  - Cpe
  - eps
  - K
  activeReactionVars:
  - A
  - E
  - n
  - Hp
  - nO2
  - Xi
  backBoundaryConditions:
    Tamb: 25
    htc: Auto
    type: INSULATED
  columns:
  - 1
  depths:
  - 0
  file: C:/Users/Fyang/Workspace/optimization/optimizationPaper/data/multiReactionCharring/multiReactionCharringFake.csv
  frontBoundaryConditions:
    Tamb: 25
    heatFlux: 100.0
    htc: 15
  initialThickness: 0.008
  names:
  - Mass
  time: 0
  types:
  - 1
  weight: 1.0
  weights:
  - 1
  width1: 0.1016
  width2: 0.1016
dataSources:
  names:
  - cone1
  types:
  - cone
fdsPath: C:\Program Files\FDS\FDS6\bin
keepTemporaryFiles: true
name: charLinear3Reac4Mass100kW
outputParams:
  saveAllSamples: true
phaseParams:
  C0:
  - - 1
    - 0
    - 1
  - - 0
    - 1189
    - 1189
  Cpa:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - &id001 !!python/object/apply:numpy.dtype
        args:
        - f8
        - 0
        - 1
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        t4Acs5jYjkA=
    - 1000
    - 2800
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        a4WCj4jLiEA=
    - 1189
    - 1189
  Cpb:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        5hD8nukgxz8=
    - 0.0
    - 0.0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        g+BZHpdb0D8=
    - 1189
    - 1189
  Cpc:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  Cpd:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  K:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        GiTABop/40A=
    - 500
    - 3000
  - - 1e8
    - 1189
    - 1189
  eps:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        uVHO32kX7j8=
    - 0.75
    - 1.0
  - - 0.94
    - 1189
    - 1189
  ka:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        akHsfiSJ0j8=
    - 0.1
    - 0.3
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        XxmaWFQxzz8=
    - 1189
    - 1189
  kb:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        CxhWiwg+Ez8=
    - 0.0
    - 0.0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        5FIe+IYMFD8=
    - 0.0
    - 0.0
  kc:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  kd:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  nO2:
  - - 0
    - 0
    - 1
  - - 0
    - 1189
    - 1189
  phases:
  - virgin
  - char
  rho:
  - - 1683
    - 1189
    - 1189
  - - 1235
    - 1189
    - 1189
processParams:
  maxProcesses: 8
  multiprocess: true
reactionParams:
  A:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAiqaVZkI=
    - 1e6
    - 1e14
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AADgV+tI60I=
    - 1e6
    - 1e14
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAC4Bm5gvUI=
    - 1e6
    - 1e14
  E:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAFBEE=
    - 1.2e4
    - 2.0e5
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAABqCEE=
    - 1.2e4
    - 2.0e5
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAOA5E0E=
    - 1.2e4
    - 2.0e5
  Hp:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        RK3/OJt7E0E=
    - 1e5
    - 1e7
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        E/4PpQ9yDUE=
    - 1e5
    - 1e7
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        eo9yc3LaMkE=
    - 1e5
    - 1e7
  Xi:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        P6VqUPRO2T8=
    - 0
    - 1
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        iLh58FH74D8=
    - 0
    - 1
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        2flkOe7Asz8=
    - 0
    - 1
  n:
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        BjrpZMA8/j8=
    - 5e-1
    - 4e0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        Kx+u5+Aa9D8=
    - 5e-1
    - 4e0
  - - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        aHqMLJTfGEA=
    - 5e-1
    - 4e0
  nO2:
  - - 0
    - 0
    - 1
  - - 0
    - 0
    - 1
  - - 0
    - 0
    - 1
  prodState:
  - 1
  - 1
  - 1
  reacState:
  - 0
  - 0
  - 0
  typeState:
  - 3
  - 3
  - 3
reinitializeComplex: false
resultsDir: ../../../../results/multiReactionCharring/3Reactions/validation/
virtualExperiment: true
