name: multiReacCharLinearHybrid100KW
resultsDir: '../../../results/multiReactionCharring/validation/'
virtualExperiment: True
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: False
keepTemporaryFiles: True
outputParams:
  saveAllSamples: True
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 100
  file: '../../../data/multiReactionCharring/multiReacCharLinearNominal100KW_0_cone_Mass.csv'
  time: 0
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 8
phaseParams:
  phases: ['virgin', 'char']
  C0:   [[1,      0,      1], [0,  1189,   1189]      ]
  ka:   [[0.329,     0.10,   0.30], [0.1845,  1189,   1189]   ]
  kb:   [[4.088e-5,      0.0,    0.0], [1.45e-4,  0.0,   0.0]     ]
  kc:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  kd:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  rho:  [[1683,  1189,   1189], [1235,  1189,   1189]   ]
  Cpa:  [[1120,     1000,   2800], [658.7,  1189,   1189]   ]
  Cpb:  [[4.85e-2,      0.0,    0.0], [8.72e-1,  1189,   1189]    ]
  Cpc:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  Cpd:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  eps:  [[0.966,     0.75,   1.0], [0.94,  1189,   1189]    ]
  K:    [[35904,     500,    3000], [1e8,  1189,   1189]   ]
  nO2:  [[0,        0,      1], [0,  1189,   1189]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[2.47e12,1e6,1e14], [8.16e13,1e6,1e14]]
  E:   [[1.78e5,1.2e4,2.0e5], [1.95e5,1.2e4,2.0e5]]
  n:   [[1.0735,5e-1,4e0], [1.577,5e-1,4e0]]
  Hp:  [[120269,1e5,1e7], [231900,1e5,1e7]]
  nO2: [[0,0,1], [0,0,1]]
  Xi:  [[0.75,0,1], [0.5,0,1]]
  typeState: [3,3]
  reacState: [0,0]
  prodState: [1,1]
