name: multiReacLinearHybrid
resultsDir: '../../../results/multiReactionCharring/hybrid/'
virtualExperiment: False
keepTemporaryFiles: True
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: False
outputParams:
  saveAllSamples: False
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 25
  file: '../../../data/multiReactionCharring/multiReactionCharringLinearNominal_0_cone_Mass.csv'
  time: 0
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  finalThickness: 0.0063498751
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 4
optimizeParams:
  opP: 41
  opS: 41
  opQ: 21
  opAlpha: 1
  opBeta: 41
  minP: 21
  minIter: 5
  maxIter: 1000
  absErr: 1e-7
  relErr: 1e-12
  absRelErr: 5e-7
  relIter: 15
  maxTime: 60000
  elimThresh: 1e-2
phaseParams:
  phases: ['virgin', 'char']
  C0:   [[1,      0,      1], [0,  1189,   1189]      ]
  ka:   [[None,     0.078,   1.248], [None,  0.023725,  0.3796]   ]
  kb:   [[None,     1.1013e-5,    1.762e-4], [None,  7.075e-5,   1.132e-3]     ]
  kc:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  kd:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  rho:  [[1683,  1189,   1189], [1235,  1189,   1189]   ]
  Cpa:  [[None,     972,   1188], [None,  260.25,   4164]   ]
  Cpb:  [[None,     0.04068,    0.04972], [None,  6.475e-2,   1.036]    ]
  Cpc:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  Cpd:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  eps:  [[None,     0.235,   1.0], [0.94,  0.235,   1.0]    ]
  K:    [[None,    2500,    40000], [1e8,  1189,   1189]   ]
  nO2:  [[0,        0,      1], [0,  1189,   1189]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[None,2.106e12,2.574e12], [None,6.75e13,8.25e13]]
  E:   [[None,1.629e5,1.991e5], [None,1.737e5,2.123e5]]
  n:   [[None,0.9,1.1], [None,1.35,1.65]]
  Hp:  [[None,2.5e4,4e5], [None,5e4,8e5]]
  nO2: [[0,0,1], [0,0,1]]
  Xi:  [[None,0.675,0.825], [None,0.45,0.55]]
  typeState: [3,3]
  reacState: [0,0]
  prodState: [1,1]
