name: E_GlassLinearHybrid35KW
resultsDir: '../../../results/E_Glass/'
virtualExperiment: True
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: False
outputParams:
  saveAllSamples: True
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 35
  file: '../../../data/E_Glass/E_GlassLinearNominal35KW_0_cone_Mass.csv'
  time: 0
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 4
phaseParams:
  phases: ['virgin', 'char']
  C0:   [[1,      0,      1], [0,  1189,   1189]      ]
  ka:   [[0.327,     0.10,   0.30], [0.02374,  1189,   1189]   ]
  kb:   [[1.1396e-5,      0.0,    0.0], [3.409e-4,  0.0,   0.0]     ]
  kc:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  kd:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  rho:  [[1683,  1189,   1189], [1235,  1189,   1189]   ]
  Cpa:  [[1058.556,     1000,   2800], [1048.729,  1189,   1189]   ]
  Cpb:  [[4.50e-2,      0.0,    0.0], [0.4266,  1189,   1189]    ]
  Cpc:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  Cpd:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  eps:  [[0.7243,     0.75,   1.0], [0.795,  1189,   1189]    ]
  K:    [[11798.78,     500,    3000], [0,  1189,   1189]   ]
  nO2:  [[0,        0,      1], [0,  1189,   1189]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[3.81e+15,1e6,1e14]]
  E:   [[1.97e+05,1.2e4,2.0e5]]
  n:   [[1.7,5e-1,4e0]]
  Hp:  [[594215.7,1e5,1e7]]
  nO2: [[0,0,1]]
  Xi:  [[None,0,1]]
  typeState: [3]
  reacState: [0]
  prodState: [1]
