name: E_GlassOldLinearTight
resultsDir: '../../results/E_Glass/'
virtualExperiment: False
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: True
outputParams:
  saveAllSamples: False
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 25
  file: '../../data/E_Glass/E_GlassOldLinearNominal_0_cone_Mass.csv'
  time: 0
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 4
optimizeParams:
  opP: 29
  opS: 29
  opQ: 15
  opAlpha: 57
  opBeta: 1
  minP: 2
  minIter: 5
  maxIter: 1000
  absErr: 1e-7
  relErr: 1e-12
  absRelErr: 5e-7
  relIter: 15
  maxTime: 60000
  elimThresh: 1e-2
phaseParams:
  phases: ['virgin', 'char']
  C0:   [[1,      0,      1], [0,  1189,   1189]      ]
  ka:   [[None,     0.2496,   0.3744], [None,  0.07592,   0.11388]   ]
  kb:   [[None,     3.524e-5, 5.286e-5],  [None,  2.264e-4, 3.396e-4]     ]
  kc:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  kd:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  rho:  [[1683,  1189,   1189], [1235,  1189,   1189]   ]
  Cpa:  [[None,     864,    1296], [None,  832.8,   1.2492e3]   ]
  Cpb:  [[None,     3.616e-2,   5.424e-2], [None,  2.072e-1,   3.108e-1]    ]
  Cpc:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  Cpd:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  eps:  [[None,     0.752,   1.0], [0.94,  0.752,   1.0]    ]
  K:    [[None,     8000,    12000], [1e8,  1189,   1189]   ]
  nO2:  [[0,        0,      1], [0,  1189,   1189]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[None,1.8752e12,2.8128e12]]
  E:   [[None,1.448e+05,2.172e+05]]
  n:   [[None,0.8,1.2]]
  Hp:  [[None,8.0e4,1.2e5]]
  nO2: [[0,0,1]]
  Xi:  [[None,0,1]]
  typeState: [3]
  reacState: [0]
  prodState: [1]
