name: E_GlassConstTight
resultsDir: '../../results/E_Glass/'
virtualExperiment: False
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: True
outputParams:
  saveAllSamples: False
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 25
  file: '../../data/E_Glass/E_GlassConstNominal_0_cone_Mass.csv'
  time: 0
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 4
optimizeParams:
  opP: 12
  opS: 24
  opQ: 6
  opAlpha: 3
  opBeta: 3
  minP: 2
  minIter: 5
  maxIter: 1000
  absErr: 1e-7
  relErr: 1e-12
  absRelErr: 5e-7
  relIter: 15
  maxTime: 36000
  elimThresh: 1e-2
phaseParams:
  phases: ['virgin', 'char']
  C0:   [[1,      0,      1], [0,  1189,   1189]      ]
  ka:   [[None,     0.24,   0.36], [None,  0.16,   0.24]   ]
  kb:   [[0.0,      0.0,    0.0],  [0.0,  0.0,   0.0]     ]
  kc:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  kd:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  rho:  [[1683,  1189,   1189], [1235,  1189,   1189]   ]
  Cpa:  [[None,     872,   1308], [None,  920,   1380]   ]
  Cpb:  [[0.0,      0.0,    0.0], [0.0,  1189,   1189]    ]
  Cpc:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  Cpd:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  eps:  [[None,     0.752,   1.0], [None,  0.752,   1.0]    ]
  K:    [[None,     8000,    12000], [1e8,  1189,   1189]   ]
  nO2:  [[0,        0,      1], [0,  1189,   1189]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[None,2.704e+15,4.056e+15]]
  E:   [[None,1.704e+05,2.556e+05]]
  n:   [[None,1.2,1.8]]
  Hp:  [[None,4.76e5,7.14e5]]
  nO2: [[0,0,1]]
  Xi:  [[None,0,1]]
  typeState: [3]
  reacState: [0]
  prodState: [1]
