name: PMMALinearNominal
resultsDir: '../../../results/PMMA/'
virtualExperiment: True
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: False
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
  file: '../../../data/PMMALinearFake1.csv'
  time: 0
  heatFlux: 20
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  thickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: False
  maxProcesses: 4
phaseParams:
  phases: ['virgin']
  C0:   [[1.0,      0,      1]      ]
  ka:   [[0.2,     0.10,   0.30]   ]
  kb:   [[0.0001,      0.0,    0.0]    ]
  rho:  [[1189.37,  1189,   1189]   ]
  Cpa:  [[1100,     1000,   2800]   ]
  Cpb:  [[0.002,      0.0,    0.0]    ]
  eps:  [[0.8,     0.75,   1.0]    ]
  K:    [[1000,     500,    3000]   ]
  nO2:  [[0,        0,      1]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[5.08e+10,  4e8,    7e12]]
  E:   [[1.57e+05,  1.20e5, 2.0e5]]
  n:   [[0.91,  0.73,   1.5]]
  Hp:  [[788000,  630e3,  945e3]]
  typeState: [3]
  reacState: [0]
  prodState: [-1]
