name: PMMAConstTight
resultsDir: '../../results/PMMA/'
virtualExperiment: False
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: False
outputParams:
  saveAllSamples: True
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 25
  file: '../../data/PMMA/PMMAConstNominal_0_cone_Mass.csv'
  time: 0
  heatFlux: 20
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 4
optimizeParams:
  opP: 8
  opS: 16
  opQ: 4
  opAlpha: 3
  opBeta: 3
  minP: 2
  minIter: 5
  maxIter: 1000
  absErr: 1e-7
  relErr: 1e-12
  absRelErr: 1e-6
  relIter: 15
  maxTime: 36000
  elimThresh: 1e-2
phaseParams:
  phases: ['virgin']
  C0:   [[1.0,      0,      1]      ]
  ka:   [[None,    0.1992,   0.2988]   ]
  kb:   [[0.0,      0.0,    0.0]    ]
  kc:   [[0.0,      0.0,    0.0]    ]
  kd:   [[0.0,      0.0,    0.0]    ]
  rho:  [[1189.37,  1189.37,   1189.37]   ]
  Cpa:  [[None,     1509,   2263]   ]
  Cpb:  [[0.0,      0.0,    0.0]    ]
  Cpc:  [[0.0,      0.0,    0.0]    ]
  Cpd:  [[0.0,      0.0,    0.0]    ]
  eps:  [[None,     0.64,   0.96]    ]
  K:    [[None,     800,    1200]   ]
  nO2:  [[0,        0,      1]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[None,4.064e10,6.096e10]]
  E:   [[None,1.256e5,1.884e5]]
  n:   [[None,0.728,1.092]]
  Hp:  [[None,6.304e5,9.456e5]]
  nO2: [[0,0,1]]
  Xi: [[0,0,1]]
  typeState: [3]
  reacState: [0]
  prodState: [-1]
