name: multiReacCharLinearHybrid10KW
resultsDir: '../../../results/multiReactionCharring/validation/'
virtualExperiment: True
fdsPath: 'C:\Program Files\FDS\FDS6\bin'
reinitializeComplex: False
keepTemporaryFiles: True
outputParams:
  saveAllSamples: True
cone1:
  activePhaseVars: ['C0','rho','ka','kb','kc','kd','ke','Cpa','Cpb','Cpc','Cpd','Cpe','eps','K']
  activeReactionVars: ['A','E','n','Hp','nO2','Xi']
  weight: 1.0
  backBoundaryConditions:
    type: 'INSULATED'
    htc: 'Auto'
    Tamb: 25
  frontBoundaryConditions:
    htc: 15
    Tamb: 25
    heatFlux: 10
  file: '../../../data/multiReactionCharring/multiReacCharLinearNominal10KW_0_cone_Mass.csv'
  time: 0
  Tinit: 25
  width1: 0.1016
  width2: 0.1016
  initialThickness: 0.008
  names: ['Mass']
  columns: [1]
  weights: [1]
  depths: [0]
  types: [1]
processParams:
  multiprocess: True
  maxProcesses: 8
phaseParams:
  phases: ['virgin', 'char']
  C0:   [[1,      0,      1], [0,  1189,   1189]      ]
  ka:   [[0.3001,     0.10,   0.30], [0.2007,  1189,   1189]   ]
  kb:   [[6.004e-5,      0.0,    0.0], [4.928e-4,  0.0,   0.0]     ]
  kc:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  kd:   [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  rho:  [[1683,  1189,   1189], [1235,  1189,   1189]   ]
  Cpa:  [[1045.04,     1000,   2800], [2496.36,  1189,   1189]   ]
  Cpb:  [[4.628e-2,      0.0,    0.0], [4.786e-1,  1189,   1189]    ]
  Cpc:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  Cpd:  [[0.0,      0.0,    0.0],  [0.0,      0.0,    0.0]  ]
  eps:  [[0.8098,     0.75,   1.0], [0.94,  1189,   1189]    ]
  K:    [[23613.58,     500,    3000], [1e8,  1189,   1189]   ]
  nO2:  [[0,        0,      1], [0,  1189,   1189]      ]
dataSources:
  names: ['cone1']
  types: ['cone']
reactionParams:
  A:   [[2.32e12,1e6,1e14], [7.29e13,1e6,1e14]]
  E:   [[1.74e5,1.2e4,2.0e5], [1.85e5,1.2e4,2.0e5]]
  n:   [[0.994,5e-1,4e0], [1.542,5e-1,4e0]]
  Hp:  [[120369,1e5,1e7], [263793,1e5,1e7]]
  nO2: [[0,0,1], [0,0,1]]
  Xi:  [[0.736,0,1], [0.51,0,1]]
  typeState: [3,3]
  reacState: [0,0]
  prodState: [1,1]
